[project]
title = "Cereal Analytics"
version = "0.1.0"
port = 8501
slug = "cereal-dashboard"
entrypoint = "hello.py"

[branding]
name = "Cereal Analytics"
logo = "images/cereal_logo.png"
favicon = "images/cereal_favicon.png"
primaryColor = "#F89613"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"