[project]
title = "Cereal Industry Analytics & Insights"
version = "0.1.0"
port = 8501
slug = "cereal-dashboard"
entrypoint = "hello.py"

[branding]
name = "Cereal Industry Analytics & Insights"
logo = "images/stack_pilot.png"
favicon = "images/stackpilot-favicon.png"
primaryColor = "#F89613"

[data.sample_csv]
type = "csv"
path = "data/cereal.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"